### ISSUE TITLE
Issue in main medicine

### ISSUE THREAD

**Issue by harshit2121** [GouveiaXS/angelicxs-diseases#2]
Hi
I having an issue that the medicine is not there and you not provided any thing about it to be added in the QB-core/shared/items.lua ?

**Comment by GouveiaXS** [comment]
Please note that this is not an issue; you need to make the items yourself. 
Fortunately for you, a different user posted the items they made for qb-core on the cfx forum page

– Medicine
coughmedicine = { name = ‘coughmedicine’, label = ‘Coughmedicine’, weight = 20, type = ‘item’, image = ‘coughmedicine.png’, unique = false, useable = true, shouldClose = true, combinable = nil, description = ‘meds for cough’ },
gingermedicine = { name = ‘gingermedicine’, label = ‘Gingermedicine’, weight = 20, type = ‘item’, image = ‘gingermedicine.png’, unique = false, useable = true, shouldClose = true, combinable = nil, description = ‘meds for dizzyness’ },
nasuamedicine = { name = ‘nasuamedicine’, label = ‘nasua medicine’, weight = 20, type = ‘item’, image = ‘nasuamedicine.png’, unique = false, useable = true, shouldClose = true, combinable = nil, description = ‘meds for nasua’ },
